### PR TITLE
fix: Support stale-while-revalidate

### LINKED ISSUE #512: Support stale-while-revalidate
Servers can send [stale-while-revalidate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate) in Cache-Control.
This allows client to do the following simultaneously:
- return the response from cache
- update the cache in background (but avoid returning it to the client)

For data that is not updated often, this allow to always be fast while also returning stale data at most once. 
So typically, hitting the refresh button on the browser would get the correct data.

This is not supported (yet) by this library, but could it be considered?

### PR DESCRIPTION
**Pull request by richardgarnier**
This PR fixes #512 
Note: this probably generate conflicts with #510

Also, I'm not completely convinced about the `hydrate` implementation. Currently, when we have a stale value we do the following:
- call the hydrate function with the stale data
- refetch the data and return result with cached === false

To me, this should be the opposite, thus:
- return the stale data with cached === true (when stale-while-revalidate allows us to do that)
- refetch the data, and call the hydrate function with the fresh data (if set)

This would allow for RFC compliance while also allowing users to get the fresh data as soon as it is available should they need it (when used on a server it does not necessarily make sense to use the double return technique).  
However, should we want to make the change above, I think the current PR can still be merged and the change above be made in another PR.

### CODE REVIEW

File: src/interceptors/response.ts [hunk 1]
```diff
@@ -155,7 +156,10 @@ export function defaultResponseInterceptor(
         return response;
       }
 
-      ttl = expirationTime === 'not enough headers' ? ttl : expirationTime;
+      if (expirationTime !== 'not enough headers') {
```
Comment (Embraser01) [inline src/interceptors/response.ts:159]: That would mean checking here if `typeof expirationTime === 'number'`

File: src/storage/build.ts [hunk 2]
```diff
@@ -20,7 +20,6 @@ export function canStale(value: CachedStorageValue): boolean {
     Header.ETag in headers ||
     Header.LastModified in headers ||
     Header.XAxiosCacheEtag in headers ||
-    Header.XAxiosCacheStaleIfError in headers ||
```
Comment (Embraser01) [inline src/storage/build.ts:23]: Seems unrelated 🤔 Also is it used somewhere else?

Comment (richardgarnier) [reply src/storage/build.ts:23]: This was an internal header, that I think should not be checked here.
I might be wrong though

File: src/header/types.ts [hunk 3]
```diff
@@ -1,6 +1,11 @@
 import type { CacheAxiosResponse } from '../cache/axios';
 
-export type InterpreterResult = 'dont cache' | 'not enough headers' | number;
+export type TtlData = {
+  cacheTtl: number;
+  staleTtl?: number;
+};
+
+export type InterpreterResult = 'dont cache' | 'not enough headers' | TtlData;
```
[the remark this answers is not in the document]
Comment (richardgarnier) [reply src/header/types.ts:8]: Sure, I'll do that tomorrow

**Review by Embraser01 — APPROVED** [review]

**Comment by arthurfiorette** [comment]
> To me, this should be the opposite, thus:
> 
>  - return the stale data with cached === true (when stale-while-revalidate allows us to do that)
>  - re fetch the data, and call the hydrate function with the fresh data (if set)

With that, we may introduce a problem due to misleading usage. Not anyone who uses axios-cache-interceptor should understand all behaviors. By doing this, their axios calls will return stale data when it shouldn't. He already expects that `axios()` will do a network travel for him, cache is only a benefit when possible.

As not using the `hydrate` option don't throw any warnings (and it shouldn't), the end-user will only have fresh data (>> That we have in cache <<) when he fetches again. I know that `re-validate` means exactly this, but for implementations that can re-execute the code when the fresh data arrives, and we cannot resolve a js promise two times.

This will lead to an behavior like this:

 - Uses `axios.get()` without `hydrate` and after the cache expired its needed to do 2 page reloads. 1  that returns immediately, does the network call asynchronously and saves it into the cache. And other that returns immediately with the newly cache.
 
 - Uses `axios.get()` with `hydrate` and do the exactly above but with only 1 refresh that calls the provided hydrate and re-render the UI automatically. The problem with this approach is that re introduces the **callback hell** for every axios call and this is not good at all for our DX.

That's why I created the `hydrate` option, that tells you like: _The cache is not valid at all, we will fetch a new one and resolve this promise with it, IF YOU REALLY want to avoid any UI flickering or letting the screen empty for some ms, you can use the hydrate option_.

I'm ok to changing the `hydrate` name to another one if it is confusing, but inverting `hydrate` and `response` behavior does more harm than good.

**Comment by arthurfiorette** [comment]
Hey @richardgarnier and @Embraser01, thanks for your work! I'll be pointing out some things that I think should change, but I'm open to discussion :)

**Comment by arthurfiorette** [comment]
> To me, this should be the opposite, thus:
> 
>  - return the stale data with cached === true (when stale-while-revalidate allows us to do that)
>  - re fetch the data, and call the hydrate function with the fresh data (if set)

With that, we may introduce a problem due to misleading usage. Not anyone who uses axios-cache-interceptor should understand all behaviors. By doing this, their axios calls will return stale data when it shouldn't. He already expects that `axios()` will do a network travel for him, cache is only a benefit when possible.

As not using the `hydrate` option don't throw any warnings (and it shouldn't), the end-user will only have fresh data (>> That we have in cache <<) when he fetches again. I know that `re-validate` means exactly this, but for implementations that can re-execute the code when the fresh data arrives, and we cannot resolve a js promise two times.

This will lead to an behavior like this:

 - Uses `axios.get()` without `hydrate` and after the cache expired its needed to do 2 page reloads. 1  that returns immediately, does the network call asynchronously and saves it into the cache. And other that returns immediately with the newly cache.
 
 - Uses `axios.get()` with `hydrate` and do the exactly above but with only 1 refresh that calls the provided hydrate and re-render the UI automatically. The problem with this approach is that re introduces the **callback hell** for every axios call and this is not good at all for our DX.

That's why I created the `hydrate` option, that tells you like: _The cache is not valid at all, we will fetch a new one and resolve this promise with it, IF YOU REALLY want to avoid any UI flickering or letting the screen empty for some ms, you can use the hydrate option_.

I'm ok to changing the `hydrate` name to another one if it is confusing, but inverting `hydrate` and `response` behavior does more harm than good.

File: src/storage/build.ts (hunk 2 above)
Comment (arthurfiorette) [reply src/storage/build.ts:23]: Keep this statement for now, unrelated to this PR. And i'll move from internal headers to a meta property on storage values soon :) Or is it causing any bugs?

File: src/storage/build.ts [hunk 4]
```diff
@@ -12,24 +12,36 @@ import type {
...
     Header.XAxiosCacheLastModified in headers
   );
 }
 
+/** Returns true if this has sufficient properties to stale instead of expire. */
+export function canStale(value: CachedStorageValue | StaleStorageValue): boolean {
```
Comment (arthurfiorette) [inline src/storage/build.ts:29]: Should be:

```suggestion
export function canStale(value: CachedStorageValue): boolean {
```

Right?

File: src/storage/build.ts [hunk 5]
```diff
@@ -12,24 +12,36 @@ import type {
...
 /**
  * Checks if the provided cache is expired. You should also check if the cache
  * {@link canStale}
  */
-export function isExpired(value: CachedStorageValue): boolean {
+export function isExpired(value: CachedStorageValue | StaleStorageValue): boolean {
+  if (value.ttl === undefined) {
+    return false;
+  }
   return value.createdAt + value.ttl <= Date.now();
```
Comment (arthurfiorette) [inline src/storage/build.ts:45]:
```suggestion
  return !value.ttl || value.createdAt + value.ttl <= Date.now();
```

File: src/storage/build.ts [hunk 6]
```diff
@@ -84,27 +138,17 @@ export function buildStorage({ set, find, remove }: BuildStorage): AxiosStorage
...
-      if (canStale(value)) {
-        const stale: StaleStorageValue = {
-          state: 'stale',
-          createdAt: value.createdAt,
-          data: value.data
-        };
-
-        await set(key, stale, config);
-        return stale;
+      switch (value.state) {
```
Comment (arthurfiorette) [inline src/storage/build.ts:141]: This switch don't fits well in this code, You can reuse some of repeated statements on `handleCachedValues` and `handleStaleValues`.

Try something like:


```ts
if(value.state === 'empty' || value.state !== 'loading') {
 return value;
}

// Non expired stale or cached are fine
if (!isExpired(value)) {
 return value;
}

// Updates to stale if possible
if(value.state === 'cached' && canStale(value)) {
 value={
  state: 'stale',
  createdAt: value.createdAt,
  data: value.data,
  ttl: value.staleTtl !== undefined ? value.staleTtl + value.ttl : undefined };

  await set(key, value, config);


// Maybe the newly value are already expired
  if (!isExpired(value)) {
      return value;
    }

}


// Can overstale because of some meta values
    if (hasUniqueIdentifierHeader(value)) {
      return value;
  }


// Cache is not valid anymore.
await remove(key, config);
return { state: 'empty' };
```

I did write this in the github comments and maybe i'm crazy bcs of that, but I think you got the idea that we can change these 2 functions declaration and a switch to just 2 if statements.

File: test/header/interpreter.test.ts [hunk 7]
```diff
@@ -42,6 +42,26 @@ describe('tests header interpreter', () => {
     });
 
     // 1 year
-    expect(result).toBe(1000 * 60 * 60 * 24 * 365);
+    expect(result).toEqual({ cacheTtl: 1000 * 60 * 60 * 24 * 365 });
+  });
+
+  it('tests with maxAge=10 and age=3 and staleWhileRevalidate headers', () => {
+    const result = defaultHeaderInterpreter({
+      [Header.CacheControl]: 'max-age=10,stale-while-revalidate=5',
```
Comment (arthurfiorette) [inline test/header/interpreter.test.ts:50]:
```suggestion
      [Header.CacheControl]: 'max-age=10, stale-while-revalidate=5',
```
😁

File: test/header/interpreter.test.ts [hunk 8]
```diff
@@ -42,6 +42,26 @@ describe('tests header interpreter', () => {
...
+      [Header.Age]: '3'
+    });
+
+    expect(result).toEqual({ cacheTtl: 7 * 1000, staleTtl: 5 * 1000 });
+  });
+
+  it('tests with expires and cache-control and staleWhileRevalidate present', () => {
+    const result = defaultHeaderInterpreter({
+      [Header.CacheControl]: 'max-age=10,stale-while-revalidate=5',
```
Comment (arthurfiorette) [inline test/header/interpreter.test.ts:59]:
```suggestion
      [Header.CacheControl]: 'max-age=10, stale-while-revalidate=5',
```
😁

File: test/interceptors/hydrate.test.ts [hunk 9]
```diff
@@ -13,8 +15,11 @@ describe('Hydrate works', () => {
     expect(mock).not.toHaveBeenCalled();
   });
 
-  it('only hydrates when cache is returned', async () => {
-    const axios = mockAxios({});
+  it('only hydrates when cache is stale', async () => {
+    const axios = mockAxios(
+      {},
+      { [Header.CacheControl]: 'max-age=100,stale-while-revalidate=100' }
```
Comment (arthurfiorette) [inline test/interceptors/hydrate.test.ts:21]:
```suggestion
      { [Header.CacheControl]: 'max-age=100, stale-while-revalidate=100' }
```
😁

File: test/interceptors/hydrate.test.ts [hunk 10]
```diff
@@ -35,8 +40,11 @@ describe('Hydrate works', () => {
     expect(res2.cached).toBe(true);
   });
 
-  it('hydrates when a new request is needed', async () => {
-    const axios = mockAxios({});
+  it('hydrates when cache is stale', async () => {
+    const axios = mockAxios(
+      {},
+      { [Header.CacheControl]: 'max-age=0,stale-while-revalidate=100' }
```
Comment (arthurfiorette) [inline test/interceptors/hydrate.test.ts:46]:
```suggestion
      { [Header.CacheControl]: 'max-age=0, stale-while-revalidate=100' }
```
😁

File: test/interceptors/response.test.ts [hunk 11]
```diff
@@ -100,6 +100,16 @@ describe('test response interceptor', () => {
     expect(resultCache.cached).toBe(true);
   });
 
+  it('tests header interpreter integration deprecated', async () => {
```
Comment (arthurfiorette) [inline test/interceptors/response.test.ts:103]: Move this to the header interpreter tests file.

```suggestion
  it('tests header interpreter returning only numbers', async () => {
```

File: src/storage/build.ts [hunk 12]
```diff
@@ -72,6 +84,48 @@ export type BuildStorage = Omit<AxiosStorage, 'get'> & {
  * @see https://axios-cache-interceptor.js.org/guide/storages#buildstorage
  */
 export function buildStorage({ set, find, remove }: BuildStorage): AxiosStorage {
+  const handleStaleValues = async (
```
Comment (arthurfiorette) [inline src/storage/build.ts:87]: Read the switch comment.

```suggestion
```

File: src/interceptors/response.ts (hunk 1 above)
Comment (arthurfiorette) [reply src/interceptors/response.ts:159]: It can be a number or an object

**Review by arthurfiorette — CHANGES_REQUESTED** [review]
Sorry if I was a bit strict :) open to discussions if you want :)

File: src/storage/build.ts (hunk 2 above)
Comment (richardgarnier) [reply src/storage/build.ts:23]: It is, because it prevents stale data from expiring correctly.

**Comment by richardgarnier** [comment]
> > To me, this should be the opposite, thus:
> > 
> > * return the stale data with cached === true (when stale-while-revalidate allows us to do that)
> > * re fetch the data, and call the hydrate function with the fresh data (if set)
> 
> With that, we may introduce a problem due to misleading usage. Not anyone who uses axios-cache-interceptor should understand all behaviors. By doing this, their axios calls will return stale data when it shouldn't. He already expects that `axios()` will do a network travel for him, cache is only a benefit when possible.
> 
> As not using the `hydrate` option don't throw any warnings (and it shouldn't), the end-user will only have fresh data (>> That we have in cache <<) when he fetches again. I know that `stale-while-revalidate` means exactly this, but for implementations that can re-execute the code when the fresh data arrives, and we cannot resolve a js promise two times.
> 
> This will lead to an behavior in a UI similar to the following:
> 
> * Uses `axios.get()` without `hydrate` and after the cache expired its needed to do 2 page reloads. 1  that returns immediately, does the network call asynchronously and saves it into the cache. And other that returns immediately with the newly cache.
> * Uses `axios.get()` with `hydrate` and do the exactly above but with only 1 refresh that calls the provided hydrate and re-render the UI automatically. The problem with this approach is that re introduces the **callback hell** for every axios call and this is not good at all for our DX.
> 
> That's why I created the `hydrate` option, it tells you like: _The cache is not valid at all, we will fetch a new one and resolve this promise with it, IF YOU REALLY want to avoid any UI flickering or letting the screen empty for some ms, you can use the hydrate option_.
> 
> I'm ok to changing the `hydrate` name to another one if it is confusing, but inverting `hydrate` and `response` behavior does more harm than good.

I disagree with this interpretation, because stale-while-revalidate explicitly allows reusing the value as if it was fresh. If treating the data as fresh while it is stale is a mistake, then the mistake is on the server side, and not on the implementation of the cache strategy.
Instead, having access to the revalidated response should be the bonus, and not the other way around, since the request fired is only intended to refresh the cache and NOT to notify the client (he already got his response from cache, since the server allowed us to do exactly this).
For anyone that does not look how the library works in detail, it is reasonable expectation that the library will behave in accordance with the specification. Please note, that this library is not necessarily used on the front-end 😄.

For reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#stale-while-revalidate

> Sorry if I was a bit strict :) open to discussions if you want :)

No worries.
As a side-note, I don't personally mind either way since we can achieve what we need by using `hydrate`.

File: src/storage/build.ts (hunk 2 above)
Comment (arthurfiorette) [reply src/storage/build.ts:23]: Alright, i'm going to move the others anyway any time soon :)

File: src/storage/build.ts [hunk 13]
```diff
@@ -78,29 +87,41 @@ export function buildStorage({ set, find, remove }: BuildStorage): AxiosStorage
...
-          data: value.data
+          data: value.data,
+          ttl: value.staleTtl !== undefined ? value.staleTtl + value.ttl : undefined
         };
+        await set(key, value, config);
+      }
 
-        await set(key, stale, config);
-        return stale;
+      if (!isExpired(value)) {
```
Comment (arthurfiorette) [inline src/storage/build.ts:119]:
```suggestion
      // A second check in case the new stale value was created already expired.
      if (!isExpired(value)) {
```

**Review by arthurfiorette — APPROVED** [review]

**Comment by arthurfiorette** [comment]
**Suuuuper** thanks for your time in this PR! Sorry that it took too long _(I moved to a state 930 miles away)_ for me to review.

**Comment by arthurfiorette** [comment]
About the hydrate discussion, took a time to search about it and still din't find a way to solve it with good DX. I'm searching second opinions and implementations out there, like [http-cache-semantics](https://github.com/kornelski/http-cache-semantics).
